title: Slider
modelClass: rendy\news\Models\Slider
list: $/rendy/news/models/slider/columns.yaml
recordUrl: 'rendy/news/slider/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
